name: Build image for fitlins test

on:
  push:
    branches-ignore:
      - '/doc\/.*/'
    tags:
      - '/.*/'
  pull_request:
    branches-ignore:
      - '/doc\/.*/'
    tags:
      - '/.*/'

jobs:
  docker:
    runs-on: docker:18.01.0-ce-git 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push cpu image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/cpu.Dockerfile
          push: true
          tags: shashankbansal56/nondefaced-detector:latest-cpu
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


